COPY Students(studentId, StudentName, Address, BirthyearStudent, Gender) FROM '/mnt/ramdisk/tables/Students.table' DELIMITER ',' CSV HEADER;
COPY courseregistrations(courseofferid, studentregistrationid, grade) FROM '/mnt/ramdisk/tables/CourseRegistrations.table' DELIMITER ',' CSV HEADER NULL as 'null';
COPY degrees(degreeId, dept, degreedescription,totalects) FROM '/mnt/ramdisk/tables/Degrees.table' DELIMITER ',' CSV HEADER NULL as 'null';
COPY StudentRegistrationsToDegrees(StudentRegistrationId, Studentid, degreeId, registrationyear) FROM '/mnt/ramdisk/tables/StudentRegistrationsToDegrees.table' DELIMITER ',' CSV HEADER NULL as 'null';
COPY teachers(teacherid, teachername, address, birthyearteacher, gender) FROM '/mnt/ramdisk/tables/Teachers.table' DELIMITER ',' CSV HEADER;
COPY courses(courseid, coursename, coursedescription, degreeid, ects) FROM '/mnt/ramdisk/tables/Courses.table' DELIMITER ',' CSV HEADER;
COPY TeacherAssignmentsToCourses(courseofferid, teacherid) FROM '/mnt/ramdisk/tables/TeacherAssignmentsToCourses.table' DELIMITER ',' CSV HEADER;
COPY studentassistants(courseofferid, studentregistrationid) FROM '/mnt/ramdisk/tables/StudentAssistants.table' DELIMITER ',' CSV HEADER;
COPY courseoffers(courseofferid, courseid, year, quartile) FROM '/mnt/ramdisk/tables/CourseOffers.table' DELIMITER ',' CSV HEADER;
alter table studentassistants add primary key(courseofferid, studentregistrationid);
alter table courseregistrations add primary key (courseofferid, studentregistrationid);
alter table courseoffers add column coursename varchar(50), add column ects smallint, add column degreeid int;
update courseoffers set coursename = courses.coursename from courses where courseoffers.courseid = courses.courseid;
update courseoffers set ects = courses.ects from courses where courseoffers.courseid = courses.courseid;
update courseoffers set degreeid = courses.degreeid from courses where courseoffers.courseid = courses.courseid;
alter table courseoffers add primary key (courseofferid);
alter table studentregistrationstodegrees add column totalects smallint;
update studentregistrationstodegrees set totalects = degrees.totalects from degrees where studentregistrationstodegrees.degreeid = degrees.degreeid;
alter table studentregistrationstodegrees add primary key(studentregistrationid);
CREATE TABLE greaterFive AS SELECT  courseregistrations.studentregistrationid, studentid, studentregistrationstodegrees.degreeid, courseName, grade, year, quartile, ects FROM courseregistrations, studentregistrationstodegrees, courseoffers WHERE studentregistrationstodegrees.studentregistrationid = courseregistrations.studentregistrationid AND  grade >= 5 AND courseregistrations.courseofferid = courseoffers.courseofferid;
CREATE TABLE failedcourses AS  SELECT distinct studentregistrationid FROM courseregistrations WHERE grade < 5;
create table studenttotalcredits as (SELECT  courseRegistrations.studentregistrationid, SUM(case when courseRegistrations.grade >= 5 then courseoffers.ects else 0 end) as totalects, SUM(case when courseRegistrations.grade >= 5 then courseoffers.ects*courseRegistrations.grade else 0 end) AS gradeects FROM courseregistrations, courseoffers WHERE courseregistrations.courseofferid = courseoffers.courseofferid GROUP BY courseRegistrations.studentregistrationid);
